### ISSUE TITLE
Interactive prompt instead of toml upload for role menu

### ISSUE THREAD

**Issue by DiscordLiz** [mikeshardmind/discord-rolebot#1]
Thanks for getting this separated out from the other bot features and up for review and use.

There's a few people pushing to go back to the old version that required message content if we don't have an interactive menu for this. I think they're being entitled asses about it and don't care if they see me criticizing them for that here since the role menus we need are setup already, but I'll pass along the feature request anyhow.

**Comment by mikeshardmind** [comment]
Feel free to kick it and put a public bot in (oh wait, we already know why nobody wants that...)

On a serious note, if you want to work on it, I don't have strong preferences on how it should be done, but I agree the current way is only "Good enough" and should be improved on. Keeping some amount of short-lived state in memory is fine for this, I'm not going to reject a UX improvement for not keeping this as stateless as it is, the primary goal was the long-term minimal resource use.

If you'd rather not, It's currently sitting below getting the one other low-resource bot we agreed should be split out finished, and a few other things I agreed to do outside of that community on my personal priority list, so maybe about two weeks out on doing anything with this, but not something I intend to let languish if nobody else is interested in making it happen either.

**Comment by mikeshardmind** [comment]
Well, taking a little longer to get to this than I intended...

Just checking the following covers everything you can think of for now.

The interactive prompt starts by asking the user what the message displayed should say.
Then it starts asking per button:
- user-visible text/emoji.
- Then asks if it's to toggle a role, or to add/remove roles
- Based on those, it gets the role(s) to modify
- Then it asks about conditions.
- Then it asks if you want to add another button (looping up to the start of the per button bit if so)

**Comment by DiscordLiz** [comment]
Sure. Don't even need it to allow emoji.

**Comment by DiscordLiz** [comment]
As we talked about in person, this isn't needed anymore since the community this was for is not remaining on discord.
