### ISSUE TITLE
Possible typos in tree hash comparison

### ISSUE THREAD

**Issue by Sachaa-Thanasius** [mikeshardmind/discord-rolebot#3]
I've been coming to this repo recently for inspiration and noticed a possible bug along with maybe an artifact from a previous commit: 

```Python

with path.open(mode="w+b") as fp:
    data = fp.read()
    if data != tree_hash:
        await self.tree.sync()
        fp.seek(0)
        fp.write(tree_hash)

await self.tree.sync()
```

This is in the bot's setup hook, and I have two questions about it:

- Is the second sync after the conditional block meant to be gone, since the bot conditionally syncs just a few  lines earlier?
- Should the file mode be "r+b", since "w+b" will, to my knowledge, truncate the file immediately and leave nothing to be read? The conditional would fail every time as a result, which seems unintentional. EDIT: After a bit of research, I've realized r+b won't allow you to create the .hash file in the first place. Not sure what the best solution to this is then beyond maybe a try except with different modes, or using "a+b" and seeking back to the start before reading. Assuming this is an issue, you'll probably have a better idea than I.

Hope these make sense. Assuming they're valid, they feel like typos more than anything off in the logic. Cheers for the cool project.

**Comment by mikeshardmind** [comment]
Yep, there are both things that should be fixed. 

Second sync being there was just an error in restructuring not removing it.
w+b was me forgetting that even though + is specifically for updating, w truncation doesn't go away. This really makes the ability to combine w and + somewhat worthless.

I'm glad you're enjoying it, and thanks for pointing these out, they're both fixed in b2ff08af355da9f4415970cda84198a0bdc4f89e

**Comment by Sachaa-Thanasius** [comment]
Cheers. One last question: Is there somewhere in the code that you're ensuring "tree.hash" exists before attempting to access it? Maybe I'm missing something, but as far as I can tell, if the file doesn't exist yet, opening it with "r+b" will fail. That's why I mentioned "a+b" in my previous comment's edit.

**Comment by mikeshardmind** [comment]
> Cheers. One last question: Is there somewhere in the code that you're ensuring "tree.hash" exists before attempting to access it? Maybe I'm missing something, but as far as I can tell, if the file doesn't exist yet, opening it with "r+b" will fail. That's why I mentioned "a+b" in my previous comment's edit.

*sigh* I really dislike python's stringly-typed apis. Nope, this is just me needing to pay more attention, however I don't really want to use "a" here for two reasons:

1. The stream position is *always* the end of the file
2. This delegates the file permissions the file will be created with if created to python, and I've been meaning to more proactively use mode=... in file creations to not be world read-writable (python's unfortunate defaults)

I've still gone ahead and rectified this (and more of the second point). I might later make a little wrapper or linting rule for known things like this with python's file apis that I don't find are easy for me to remember consistently.

**Comment by Sachaa-Thanasius** [comment]
Thanks for explaining! A few details there I wasn't aware of, and some I definitely need to do more research to fully understand the implications of when it comes to security 😄.
