### ISSUE TITLE
Hey there!

### ISSUE THREAD

**Issue by BaronXOfficial** [mikeshardmind/discord-rolebot#5]
Hey, I know this is an unorthodox means of reaching out, but I saw your post in the Discord.py Discord but saw you had since left the discord server. 

![image](https://github.com/mikeshardmind/discord-rolebot/assets/48777460/96d7ad18-c8ce-4b74-a2d8-ef4646a8d3df)

I was curious if you have more information how one would implement this if one DID want to do the extra work to make it happen - any resources or information you can provide would be hugely valuable! I'm hoping to create the following:

Music Player which is also able to play sound effects over the currently playing music track eg welcome messages etc, and also it'd be very nice to be able to implement crossfading between the previous and current tracks. All of the above I expect will require such rigging. I'd be very appreciative of any information you can provide!

Thanks so much!

Baron

**Comment by mikeshardmind** [comment]
I haven't kept up with any recent changes to lavalink, discord.py, or bot handling of voice in discord in general. I know discord is actively changing some things here, but the overall premise below should be fine.

You need a way to mix this in realtime. The simplest way would be a virtual audio device managed by your system that multiple things can independently play to, and which your bot uses to send to discord. 

Could be some scaling concerns with that approach, as well as resource limit based reasons not to. You can work around these, but you're making the host sound system part of your architecture with this route. I personally think it's fine to do this as long as you plan for it, but there's certainly tradeoffs.

The other alternative is bespoke realtime mixing of audio sources. There's libraries for this, so you don't need to completely reinvent the wheel, but you'll need to do a lot more yourself still, and you can't just call into these libraries from python, they'll need proper isolation from your bot's event loop given the GIL and the concerns related with realtime audio mixing, so you'll want dedicated worker procces(es) for this.

Not much more to add here really. One option is make a virtual audio device and use it, The other is do all the same work as the sound system does for a virtual audio device to not be reliant on the sound system.
